In [ ]:
!pip install torch

===============uv init
uv *add* ===========

In [ ]:
!pip install numpy scikit-learn

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [ ]:
torch.cuda.device(0)

============Tensor============

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tensor = torch.Tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
arr*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
tensor*5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

In [ ]:
arr.sum()

np.int64(21)

In [ ]:
tensor.sum()

tensor(21.)

In [ ]:
tensor = torch.from_numpy(arr)

In [ ]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
torch.ones((2,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
np.random.random((2,4))

array([[0.92275988, 0.10144084, 0.27368358, 0.31375926],
       [0.66127847, 0.02948554, 0.2528929 , 0.52752439]])

In [ ]:
torch.rand((2,4))

tensor([[0.8249, 0.7027, 0.1856, 0.3270],
        [0.8456, 0.4156, 0.6359, 0.9298]])

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.device

'cpu'

In [ ]:
tensor.shape

torch.Size([2, 3])

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor.dtype

torch.int64

In [ ]:
arr.to_device('cude')

ValueError: Unsupported device: cude.

In [ ]:
tensor.to('cuda')

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [ ]:
tensor.sum()

tensor(21)

In [ ]:
tensor.cpu().numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# .to(device)

In [ ]:
a = torch.tensor([2.0, 3.0], requires_grad=True)
b = torch.tensor([6.0, 4.0], requires_grad=True)

f = 3 * a**3 - b**2


In [ ]:
f

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [ ]:
f.backward(gradient=torch.tensor([1.0, 1.0]))

In [ ]:
a.grad

tensor([36., 81.])

In [ ]:
9 * a**2

tensor([36., 81.], grad_fn=<MulBackward0>)

In [ ]:
b.grad

tensor([-12.,  -8.])

In [ ]:
- 2*b

tensor([-12.,  -8.], grad_fn=<MulBackward0>)

============Neural Network==============

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train_sclaed = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_sclaed

array([[ 1.45920101,  1.68871181,  1.47865523, ...,  0.96734324,
         1.27485046,  1.55889296],
       [ 0.32475583,  0.73158099,  0.28255516, ...,  0.11483027,
         0.46033635,  0.75068485],
       [-0.79547325,  0.46047251, -0.80871075, ..., -0.49245177,
        -0.10670969,  0.22961789],
       ...,
       [ 0.08023882,  0.10921022,  0.09930173, ...,  0.6318283 ,
        -0.2886233 ,  0.51842203],
       [ 1.754896  ,  1.82780225,  1.6850217 , ...,  0.83313726,
         0.42100368, -0.23213612],
       [-0.08182478,  0.06913331, -0.14008338, ..., -0.85663799,
        -0.62458989, -0.83524341]])

In [ ]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,

In [ ]:
X_train_sclaed_tensor = torch.from_numpy(X_train_sclaed).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [ ]:
train_dataset = TensorDataset(X_train_sclaed_tensor, y_train_tensor)

In [ ]:
X_train_sclaed_tensor.shape

torch.Size([455, 30])

In [ ]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [ ]:
class BCNet(nn.Module):
    def __init__(self):
        super(BCNet, self).__init__()
        self.fcl1 = nn.Linear(30, 64)

        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.dropout = nn.Dropout(0.5)
        # self.relu = nn.ReLU()
        # self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = F.relu(self.fcl1(x))
        x = F.relu(self.fc2(x))
        X = self.dropout(x)
        x = F.sigmoid(self.fc3(x))

        return x

In [ ]:
model = BCNet()

In [ ]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [ ]:
epochs = 20

for epoc in range(epochs):
  model.train()
  running_loss = 0.0

  for x_batch, y_batch in train_loader:
    optimizer.zero_grad()
    preds = model(x_batch)
    loss = criterion(preds, y_batch)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  print(f'Epoch: {epoc+1}, Loss: {running_loss/len(train_loader)}')

Epoch: 1, Loss: 0.6163447817166646
Epoch: 2, Loss: 0.4573389828205109
Epoch: 3, Loss: 0.30445609788099925
Epoch: 4, Loss: 0.17492842425902685
Epoch: 5, Loss: 0.1292229972779751
Epoch: 6, Loss: 0.09520011444886525
Epoch: 7, Loss: 0.07966522021840015
Epoch: 8, Loss: 0.07138993050903082
Epoch: 9, Loss: 0.06908720334370931
Epoch: 10, Loss: 0.06052115485072136
Epoch: 11, Loss: 0.05611873865127563
Epoch: 12, Loss: 0.05222002070707579
Epoch: 13, Loss: 0.05182758035759131
Epoch: 14, Loss: 0.047081380523741244
Epoch: 15, Loss: 0.043659529214104015
Epoch: 16, Loss: 0.0604148767888546
Epoch: 17, Loss: 0.04120561759918928
Epoch: 18, Loss: 0.037924470178162056
Epoch: 19, Loss: 0.034920091088861224
Epoch: 20, Loss: 0.033639878034591675


In [ ]:
with torch.no_grad():
  model.eval()

  preds = model(X_test_scaled_tensor)
  # preds = (preds > 0.5).float
  loss = criterion(preds, y_test_tensor).item()

  accuracy = ((preds > 0.5).float() == y_test_tensor).float().mean().item()

In [ ]:
accuracy

0.9473684430122375